// <auto-generated />
using Erantissen_Backend.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erantissen_Backend.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221204211244_asd")]
    partial class asd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Erantissen_Backend.Data.Models.CategoryDto", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Erantissen_Backend.Data.Models.HeroDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heading")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paragraph")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hero", (string)null);
                });

            modelBuilder.Entity("Erantissen_Backend.Data.Models.ProductDto", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BoughtNoOfTimes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SubcategoryTitle")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Title");

                    b.HasIndex("SubcategoryTitle");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Erantissen_Backend.Data.Models.SubcategoryDto", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.HasIndex("CategoryTitle");

                    b.ToTable("Subcategories", (string)null);
                });

            modelBuilder.Entity("Erantissen_Backend.Data.Models.ProductDto", b =>
                {
                    b.HasOne("Erantissen_Backend.Data.Models.SubcategoryDto", "Subcategory")
                        .WithMany("Products")
                        .HasForeignKey("SubcategoryTitle")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("Erantissen_Backend.Data.Models.SubcategoryDto", b =>
                {
                    b.HasOne("Erantissen_Backend.Data.Models.CategoryDto", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryTitle")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Erantissen_Backend.Data.Models.CategoryDto", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Erantissen_Backend.Data.Models.SubcategoryDto", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
